dill/dill.py, tests/test_properties.py
Fix for #81. Adds a `save_property` function that converts properties into getter, setter, deleter and doc, which are the arguments to the property constructer. Adds the log entry `Pr: <property object at 0xXXXXXXXXXXXX>` when pickling a property. A test (based on the issue) is in `tests/test_properties.py`.
=> Add support for properties

dill/dill.py
For #91. Could @lebedov please try this? And should we check for `sys.exec_prefix`, `sys.base_exec_prefix` and `sys.prefix` as well?
=> Check for sys.real_prefix when serialising module

dill/dill.py
Setting split_imports=True will preprocess the module by groveling
through its top-level objects for things that are identical to those in
the other available modules. If it finds matches, it records the source
module and object names and then discards the objects during pickling.
On load, it then recovers the objects by "import x as y" using the
stored x, y.
This fixes issues with nasty unpickleable things in the depths of
libraries, as well as making the sessions smaller.
Fixes #79 and most of #78 - my pylab sessions start up with some dynamic GObject horribles in `__main__`.
=> dump_session: add split_imports

dill/dill.py
Fix for #143. Move `obj.flush()` inside the `if obj.closed` checking.
=> Only flush if file is open

dill/dill.py
Fixes https://github.com/uqfoundation/dill/issues/150 by creating cell objects without the use of ctypes (courtesy of http://nedbatchelder.com/blog/201301/byterun_and_making_cells.html )
=> Fix for CellTypes when ctypes is missing

dill/dill.py
Passing `__slots__` in the dict to `type` recreates the slots, so the member descriptors are not needed. This removes them from the dict, so that recursion does not occur. Fixes #152. Tested on python 3.5 and 2.7.
=> Fix pickling of __main__ classes with __slots__

dill/dill.py
Hi, thanks for a great package!
Pickling functions with `dill` currently doesn't work with `pypy`:
```
Python 3.2.5 (b2091e973da69152b3f928bfaabd5d2347e6df46, Sep 23 2015, 09:21:00)
[PyPy 2.4.0 with GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import dill
>>>> def cool(x):
....     return x
....
>>>> s = dill.dumps(cool)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "dill/dill.py", line 197, in dumps
dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
File "dill/dill.py", line 190, in dump
pik.dump(obj)
File "/usr/local/Cellar/pypy3/2.4.0/libexec/lib-python/3/pickle.py", line 237, in dump
self.save(obj)
File …
```
=> Small fix to allow pickling functions in pypy

dill/dill.py
Dill keeps trying to serialize my `sys` module as its prefix directory isn't normalized:
```
In [11]: sys.prefix
Out[11]: '/Users/me/project/bin/.envname/bin/..'
```
=> Normalize module paths when checking prefixes

dill/dill.py
Pure-Python unpickler, available as `pickle._Unpickler`, uses `struct` to unpack
data, and the latter can also fail with `struct.error`. The default
C unpickler fails with documented and expectable `UnpicklingError`, and
is also faster.
Dill's unpickler seems to be a very thin wrapper around pickle's unpickler, so the change is not grave in any way, just somewhat more convenient for the end user.
-----
I'd like to help set up continuous integration build testing on Travis. What is the canonical way to run and depend on tests in the _tests_ folder? If the files are run sequentially and all asserts pass, the build is considered passing?
=> On Py3, use cPickle Unpickler

tests/test_check.py, tests/test_extendpickle.py, tests/test_file.py, tests/test_functors.py, tests/test_mixins.py, tests/test_nested.py, tests/test_objects.py, tests/test_properties.py, tests/test_weakref.py
These changes implement some `pytest` compatibility in tests. Note that, in order to keep compatibility with older test-running methods, an `if __name__ == '__main__'` section has been created in all test files to force execution when running tests directly with the interpreter.
This is really inconvenient and I am against it, as adding tests would imply the need to add explicit calls within that section. I guess it could be okay as a transition, though. And it is also impossible to avoid as long as `pytest` is not adopted as a dependency for running (adapted) dill tests. :wink:
=> Pytest compatibility

dill/dill.py, tests/test_classdef.py
Fixes #71. This handles `namedtuples`, instead of handing them over to pickle, with the usual results.
Things to consider:
- In python 2.5, where there are no `namedtuple`s, unpicking will fail (not pickling). Instead of raising, should it just return `tuple`?
=> Completely handle namedtuple pickling

dill/_dill.py
Currently `dump_session`/`load_session` takes filename to specify save/load location.
However, sometimes we want a location to be other than local file, such as remote storage.
In those cases, it'll be very helpful if `dump_session`/`load_session` takes file-like object as argument, just as normal `dump`/`load` do.
Fixed `dump_session` and `load_session` to take file-like object as argument.
- Did not change argument name from `filename`
- to keep backward compatibility
- Did not implement `dumps_session`/`loads_session` which returns/takes `bytes` object
- could be next step to go, but seems too much for now
=> Fixed dump|load_session to take file-like object

dill/_dill.py, dill/detect.py, tests/test_restricted.py
This change addresses Python classes serialization, that can raise an Exception on `__bool__` or `__eq__` operation. One of this specific-case classes is `pandas.DataFrame` (issue #261).
Way to reproduce:
```python
class RestrictedType:
def __bool__(*args, **kwargs):
raise Exception('Restricted function')
__eq__ = __lt__ = __le__ = __ne__ = __gt__ = __ge__ = __hash__ = __bool__
glob_obj = RestrictedType()
def restricted_func():
a = glob_obj
dill.loads(dill.dumps(restricted_func, recurse=True))
```
=> Fix comparing algorithm for serialization process

dill/_dill.py
This PR fixes `TypeError: unorderable types: NoneType() > int()` which is thrown on Python 3 when comparing the `position` variable with an integer, after `None` has been assigned to it (see #293). 
In Python 3, None is not orderable with integers anymore. We can fix this by assigning 0 instead.
=> [#293] Set position to 0 instead of None to prevent TypeError in Python 3

dill/source.py
I got warnings like
```
/cluster/home/schmittu/uhammer/venv36/lib64/python3.6/site-packages/dill/source.py:869: DeprecationWarning: invalid escape sequence \(
re.match('.*[\w\s]=\s*'+getname(name)+'\(', line)]
```
This pull request fixes them by using raw strings for the affected regular expressions.
=> fix warnings about invalid escape sequences.

dill/__diff.py
This fixes a bug in `__diff` module when it decides if an object is iterable or not. The problem is that it caches the result (`True` or `False`) for a type, but all the old-style class instances have the same type `<type 'instance'>`, so the first such an object that is passed to `get_seq` function determines the result for all the instances of all the old-style classes.
Also notice `#XXX` on `__diff.py:105` - maybe it has been added to alleviate the problem fixed in this commit?
/cc @Kontakter
=> Fix diff bug with oldstyle classes (Python 2)

dill/_dill.py, tests/shadowed_namedtuple/__init__.py, tests/shadowed_namedtuple/shadowed.py, tests/test_shadowed_namedtuple.py
This fixes a case of incorrect unpickling of a namedtuple-derived class instance in a situation when the classes' module path has been shadowed by some other object (see the test provided in the commit for details).
/cc @Kontakter
=> Fix shadowed namedtuple bug

dill/_dill.py, tests/test_functions.py
This PR fixes issue #313, failing to pickle keyword-only arguments, and test checking functions to be dumped and loaded correctly is added.
And I reluctantly used `exec` in the test to avoid syntax error with Python 2.x.
If there is better way, please point out.
=> Fix pickling keyword only arguments

dill/_dill.py
I tried to pickle `MappingProxyType`, which is a built-in type on Python3, but got the following error:
```
$ ipython
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import dill                                                                                                                               
In [2]: dill.__version__                                                                                                                          
Out[2]: '0.3.0'
In [3]: from types import MappingProxyType                                                                                                        
In [4]: m = MappingProxyType({"foo": "bar"}) …
```
=> Add support for pickling MappingProxyType on Python3

dill/_dill.py
This pull request includes the `child` argument explicitly in all the calls to the function `is_dill`. This argument is set to `True` in all of them except for those calls inside `save_module_dict`, in order to patch the error that is triggered on Windows as described in #323.
=> Patch module variables pickling on Windows (#323)

.travis.yml
* `sudo:` is no longer needed: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
* Default to `trusty`, explicitly use `xenial` where required
=> Simplify CI config

dill/_dill.py
This addresses an issue similar to #419 when using python environments which are accessed through symlinks.
=> Expanded obj.__file__ with realpath.

dill/_dill.py, tests/test_recursive.py
This is a partial bug fix for #458. It covers most reasonable cases that were not covered in #443. See #458 for more details.
=> Lift closure cell update to earliest function

dill/_dill.py, tests/test_dictviews.py, tests/test_functions.py
1) Implement save functions for dictionary view objects and LRU caches
2) Add trick to extract the dictionary directly from a `types.MappingProxyType` in CPython 3.9+
3) Use trick to preserve reference structure for dictionary view objects in Python 3.10+
Fixes #353
=> Support `dict` views and `functools.lru_cache`

dill/_dill.py, tests/test_classdef.py, tests/test_functions.py
1) Fixing pickling of `collections.namedtuple` subclasses
2) Fixes pickling `collections.namedtuple` when `__qualname__` is not `__name__`
3) Saves nonessential attributes of function objects by name instead arguments to the `_create_function` (supersedes #422) 
4) Pickles defaults of `collections.namedtuple` classes
I think it is worth debating if this is the best way to handle new attributes to the function class. Some functions have `__annotations__` but not `__kwdefaults__`. In the future, if these new attributes don't scale well, the current solution of adding them to `_create_function` could likely lead to a mess. On the other hand, these new strings would be added to all pickles whose functions that use said attributes. When many functions are pickled in one pickle, this overhead …
=> Pickle inner `collections.namedtuple`s and function attributes

dill/_dill.py, tests/test_classdef.py
Follow up on https://github.com/uqfoundation/dill/pull/450#issuecomment-1120055277
The issue seems more limited in scope, only effecting metaclasses, not all classes. Still believe it is good to get it in before dill 0.3.5 is out.
=> Fix class cell in `__new__` for metaclasses

.codecov.yml, .coveragerc, .readthedocs.yml, .travis.yml, MANIFEST.in, README.md, dill/__init__.py, docs/Makefile, pyproject.toml, setup.cfg, setup.py, tests/test_detect.py, tox.ini
remove `exec` from build in setup.py; enable support for in-place builds and pep517-compliant builds
Fixes #431
=> enable support for develop and pep517

pyproject.toml
Remove the redundant `wheel` dependency, as it is automatically added
by the setuptools build-backend.  Listing it in `pyproject.toml`
was a historical documentation mistake that was fixed recently (see
https://github.com/pypa/setuptools/commit/f7d30a9529378cf69054b5176249e5457aaf640a).
=> remove redundant `wheel` dep from pyproject.toml

dill/_dill.py
Correct save_code and _create_code for changes in [PEP 626](https://peps.python.org/pep-0626/).
Additionally saves co_lnotab for conversion from 3.10+ to 3.9-; For the reverse, uses `b''`.
fixes: #488
=> adjust save_code and _create_code for co_lnotab in PEP626

dill/_dill.py
The local variable `_byref` is assigned but never used.
CC: @anivegesana
=> Remove unused variable

dill/_dill.py, dill/_objects.py, dill/_shims.py, tests/test_dictviews.py, tests/test_objects.py, tests/test_pycapsule.py
=> Support PyCapsule

tests/__main__.py, tests/test_session.py
The created module `__test_main__` was being loaded in `__main__`.
=> tests: fix a test for session saving

dill/_dill.py
I'm tracing some problems with my "portable" mode prototype and hit a bug with references the `_dill` submodule saved as global:
```python
>>> import dill
>>> dill.dumps(dill._dill, 0)
b'cdill._shims\n_dill\np0\n.'
```
The `_dill` submodule is saved as an attribute of the `dill._shims` submodule, which is valid, but it should be just `dill._dill`.
The `_dill` submodule is special-cased to be saved as global:
https://github.com/uqfoundation/dill/blob/8e5e450b9ed8dff164fc259c468365e2235c6581/dill/_dill.py#L1807-L1810
But `pickle.whichmodule` misidentifies it as pertaining to `dill._shims`, because this entry is set earlier in `sys.modules` and it picks the first match.
---
The change fixes things for this especial case, but there is potential for new bugs related to other submodules: …
=> Fix `dill._dill` submodule being saved as `GLOBAL "dill._shims" "_dill"`

dill/_shims.py
New (hopefully more intuitive) construct to combine move_to and Getattr into one function call.
Resolves #447
=> Create a soft_def shim to combine move_to and Getattr

dill/_dill.py, dill/_objects.py
https://github.com/uqfoundation/dill/pull/449#issuecomment-1103998082
Extended the list of inaccessible Python types to include types that were added as recently as Python 3.11.
=> Incidental implementation specific types

dill/_dill.py, tests/test_dictviews.py
Fix bug in pickling MappingProxyType in PyPy 3.7+
=> Fix bug in pickling MappingProxyType in PyPy 3.7+

dill/_dill.py, tests/test_functions.py
This is a very strange use case of functions and methods that Python's pickle package doesn't handle correctly (#510). This case used to work in pre-0.3.5 dill, so let's bring back the old dill implementation.
The comments are irrelevant in Python 3.
Fixes #510
=> Bring back old method pickling function

dill/_dill.py, dill/_objects.py
1) move failing types from succeeds to failures, and succeeding types from failures to succeeds
2) update registered so matches reverse_typemap not in (builtins and types)
fixes: #518
=> correct failures,  registered, and succeeds

README.md, dill/__init__.py, dill/_dill.py, dill/detect.py, dill/logger.py, tests/test_logger.py
This is a detailed mode for the trace feature to help to better visualize the hierarchy of the objects being dumped and also to identify large child objects. If it is OK, I will write the documentation.
Usage:
```python
import dill
dill.detect.trace(True, detail=True)
pickled = dill.dumps(obj)
```
=> Add detailed trace mode showing saved object size and visual depth level

dill/tests/__main__.py, tox.ini
As things stand, the tests never fail when run via tox.
`__main__.py` runs each individual test script, but always exits
0, even if a test script exits >0.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> Fix tox tests so they will actually fail

.gitignore, dill/_dill.py, dill/tests/test_session.py
Fixes #525
New phrasing of mismatching modules error messages in load_session():
```python
>>> import dill
>>> dill.dump_module()
>>> dill.load_module(module='math')
ValueError: can't update module 'math' with the saved state of module '__main__'
>>> import types
>>> main = types.ModuleType('__main__')
>>> dill.load_module(module=main)
ValueError: can't update module-type object '__main__' with the saved state of imported module '__main__'
>>> dill.dump_module(module=main)
>>> dill.load_module(module='__main__')
ValueError: can't update imported module '__main__' with the saved state of module-type object '__main__'
```
=> fix dump_module() bugs and rename parameter 'main' to 'module'

dill/_dill.py, dill/source.py
Works for IPython and Jupyter, specially with functions and (most) classes. Fixes #346
=> Temporary quick fix for getsource() on IPython interpreter (fixes #346)

dill/_dill.py, dill/tests/test_classdef.py
I'll add some small pickling errors' fixes here while I test the "save unpickleable objects by reference" option.
=> Fix pickling errors thrown when saving some Stdlib modules

dill/_dill.py
Currently:
```python
>>> import dill
>>> dill.pickles(__builtins__)  # __builtins__.all() raises a TypeError for a missing argument
False
>>> dill.copy(__builtins__)
<module 'builtins' (built-in)>
>>> _ is __builtins__
True
```
Expected:
```python
>>> import dill
>>> dill.pickles(__builtins__, exact=True)
True
```
=> Fix `pickles()` flagging `__builtins__` as unpickleable due to the `all()` function

dill/logger.py
1. Propagation can create duplicate messages if the root logger has stdout/stderr handlers set (as observed in #540).
2. `StreamHandler()` uses the `sys.stderr` value as of the time of handler creation, `_StderrHandler()` always use the current value of `sys.stderr`.
=> Disable logging propagation, use current stderr as output

dill/_dill.py, dill/logger.py, dill/tests/test_classdef.py, dill/tests/test_weakref.py
As this is now called from `Pickler.save()`, which can be called from a dozen to thousands of times for a single "dump":
- Moved repeated logic to outside the numpy test functions
- Only create a save function once for each type
- Remove logic related to Python 2 old style classes
- Substituted black magic like comparing `id(obj1.__bound_method__) == id(obj2.__bound_method__)`* by  `type(obj1).__unbound_method__ is type(obj2).__unbound_method__)`
(*) I was surprised that it worked at all, must be some kind of optimization but this is not described in the language.
Amend to #540
=> Optimize the numpy hook

dill/session.py
Fix type of argument `module` in `load_module` in `dill/session.py`
=> Minor type fix

dill/_dill.py
=> Fix _is_builtin_module

LICENSE
see https://spdx.org/licenses/BSD-3-Clause.html
=> align LICENSE wording with BSD-3-Clause

dill/_dill.py, dill/tests/test_classdef.py
This PR is part 1 of the broken down version of #450. It extends support of metaclass pickling to features added in Python 3.0, 3.6, and 3.7 (https://peps.python.org/pep-3115/, https://peps.python.org/pep-0487/, https://peps.python.org/pep-0560/).
=> Python 3 Metaclasses [Support ABC and Enums - Part 1]

dill/_dill.py, dill/tests/test_abc.py
Adds support for pickling ABCs for Python 3.6 and higher.
=> Abstract Base Classes [Support ABC and Enums - Part 2]

dill/_dill.py
The `_is_builtin_module` function of `dill/_dill.py` has the following check in line 1587
`if not hasattr(module, "__file__"): return True`
If the check is not passed, then `os.path.realpath(module.__file__)` is called later in that function (line 1591).
This causes dill to crash when a module has `__file__` set to `None`. This PR fixes that check so that when `module.__file__ is None`, the module is recognized as not builtin.
Notes:
* Even though https://docs.python.org/3/reference/import.html#file__ specifies that when `__file__` is set it is a string, it will actually be none when importing a module without an `__init__.py` file in it.
* This PR only changes the behavior of dill to prevent TypeError crashes. Code that did not crash before is unaffected by this PR.
* No issue created …
=> Fixed crashed in _dill._is_builtin_module when a module's __file__ is None

dill/_dill.py, dill/tests/test_abc.py, dill/tests/test_classdef.py
Fixes #612. Test if values in the inherited dict are the same only if they have a qualname. If qualname is not used, then `'__module__'` is incorrectly set to `'dill._dill'` when it is `'__main__'`... and additionally, attributes defined in the super class with values that are flyweights or singletons (i.e. have the same hash) that are also defined in the derived class should always appear in the derived class's `__dict__`.
This PR also changes an assertion in test_abc that synchronizes previously incongruous behavior of ABC classes (there was a TODO note). I believe the new behavior is correct, in that is is more consistent with other classes behavior after pickling an instance of the class.
=> test for qualname in get_typedef_type

.travis.yml, dill/_dill.py, dill/_objects.py, dill/detect.py, dill/tests/test_objects.py, setup.py, tox.ini
add formal support for python 3.12, initial support for python 3.13
fixes SyntaxWarning for 3.13 in `dill.detect` and for removed module in `dill._objects`.
fixes construction of internal `PyCapsule` object `testcapsule`.
=> formal support for 3.12, initial support for 3.13

dill/logger.py
fixes #635 by guarding the `math.log` from both None and zero, and additionally incorrect calculations for size < 1.
=> add guard for math.log in Logger record size calculation

dill/_dill.py
Fixes https://github.com/uqfoundation/dill/issues/628 and fixes https://github.com/uqfoundation/dill/issues/604 : I have checked that they don't throw errors now.
Not sure if it breaks anything else - some of the tests on my machine failed on the master branch - but the tests run the exact same after this change.
Not sure if a test should be added, something like https://github.com/kelvinburke/dill-issue - but I'm not sure the best way?
Let me know what you think!
=> Import submodule properly when there is an attribute of the module with the same name

.travis.yml, dill/_dill.py
BufferedRandomType is not defined on Pyodide, so skip this type.
fixes: #643 
=> skip BufferedRandomType on pyodide

dill/_objects.py, dill/tests/test_selected.py, setup.cfg
fix: #643 more compatibility with Pyodide, in skipping `BufferedRandomType` in objects and tests.
=> further skip BufferedRandomType if does not exist

dill/_objects.py
remove unused import of dbm (which also causes issues for pyodide), further fixes #643
=> remove stray import of dbm in objects

dill/session.py
=> Add `UnpicklingError` import for `dill.load_session()` to fix #648

dill/source.py
I *believe* this fixes an off-by-one error for functions defined in the interpreter.
I am not sure how to test this as it only runs when directly instantiated in an interpreter.
Fixes https://github.com/uqfoundation/dill/issues/603.
Inline test:
```python
from dill.source import getsource
def my_decorator(foo):
s = getsource(foo)
print(s)
assert s.endswith("return 1\n")
@my_decorator
def foo():
return 1
```
**Before**
```raw
@my_decorator
def foo():
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 4, in my_decorator
AssertionError
```
**After**
```python
@my_decorator
def foo():
return 1
>>>
```
Please let me know any suggestions for how to implement a test for this!
=> fix fencepost error when getting source inside decorator in interpreter (fixes #603)

dill/__diff.py
numpy >= 2.0.0 doesn't import `numpy.ma` upon import of `numpy`.  As we need `MaskedConstant`, import `numpy.ma`. Fixes #667 
=> diff USE_NUMPY imports numpy.ma

dill/tests/test_detect.py
In python 3.13, the `f_locals` attribute can be a `FrameLocalsProxy` and not a `dict`, thus the `test_bad_objects` test needs to be modified to account for that.
=> adjust testing to account for frame.f_locals as a proxy in 3.13

dill/source.py, dill/tests/test_source.py
fixes #674 and other handling of `numpy` scalars in `dill.source`
=> better handle import strings of numpy scalars

dill/source.py, dill/tests/test_source.py, dill/tests/test_sources.py
add a more complete testing suite for `dill.source`, including updates of tests that use deprecated functions
=> more extensive testing for dill.source

.travis.yml, dill/_dill.py, dill/_objects.py, docs/requirements.txt, setup.py, tox.ini
add initial support for python 3.14
Fixes: #690 
=> add initial support for python 3.14

.travis.yml
move travis build of 3.9 to focal, as jammy recently started building `3.9.9` as opposed to `3.9.21`
=> move travis build of 3.9 to focal

dill/_objects.py, dill/tests/test_selected.py
use `dill._dill.get_file_type` to open file types from `_pyio`, as using `_pyio.open` directly causes error from call of `IOBase.__del__`.  Enables removal of some cleanup in `test_selected.py`
=> use get_file_type to open _pyio file types
